server: 
  port: 8082
spring:   servlet:    multipart:      max-file-size: 100MB      max-request-size: 100MB  application:
    name: AsianPaintsEVP
  profiles:
    active:
    - dev

jwt:
    jjwt:
        expiration: 1800000
        jwtRefreshExpirationMs: 84600000
        secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
       